-- =============================================================================
-- adsb_decoder_tb.vhd — Full Pipeline Testbench
-- =============================================================================
--
-- Reads binary I/Q test vector files (16-bit signed LE interleaved, as
-- generated by gen_test_vectors.py), computes power = I² + Q², and feeds
-- the power stream into the adsb_decoder top-level module.
--
-- Monitors all decoder outputs for valid messages and reports them as hex.
-- Also instantiates a timestamp_counter with a simulated PPS pulse.
--
-- Usage: Set the VECTOR_FILE generic to the path of a .dat test vector.
--        GHDL: ghdl -r adsb_decoder_tb -gVECTOR_FILE=vectors/single_clean.dat
-- =============================================================================

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

library std;
    use std.textio.all;

library work;
    use work.adsb_pkg.all;

entity adsb_decoder_tb is
    generic (
        VECTOR_FILE : string := "vectors/single_clean.dat";
        PREAMBLE_MESSAGE_DELAY : integer := 50;
        PREAMBLE_OUTPUT_TAP    : integer := 76
    );
end entity;

architecture tb of adsb_decoder_tb is

    constant CLK_PERIOD : time := 62.5 ns;  -- 16 MHz
    constant NUM_DEC    : positive := 8;

    -- Clock and reset
    signal clock    : std_logic := '0';
    signal reset    : std_logic := '1';
    signal sim_done : boolean := false;

    -- Timestamp counter signals
    signal counter_value  : unsigned(COUNTER_WIDTH-1 downto 0);
    signal counter_at_pps : unsigned(COUNTER_WIDTH-1 downto 0);
    signal pps_in         : std_logic := '0';
    signal pps_count      : unsigned(31 downto 0);
    signal pps_new        : std_logic;

    -- Decoder interface
    signal in_power   : signed(INPUT_POWER_WIDTH-1 downto 0) := (others => '0');
    signal in_valid   : std_logic := '0';
    signal init       : std_logic := '0';
    signal debug_rpl  : signed(INPUT_POWER_WIDTH-1 downto 0);
    signal out_messages : messages_t(NUM_DEC-1 downto 0);
    signal out_valid    : std_logic_vector(NUM_DEC-1 downto 0);
    signal out_toas     : toas_t(NUM_DEC-1 downto 0);
    signal out_rpls     : rpls_t(NUM_DEC-1 downto 0);

    -- Helper: convert a 4-bit value to hex character
    function nibble_to_hex(v : std_logic_vector(3 downto 0)) return character is
        variable n : integer;
    begin
        n := to_integer(unsigned(v));
        if n < 10 then
            return character'val(character'pos('0') + n);
        else
            return character'val(character'pos('A') + n - 10);
        end if;
    end function;

    -- Helper: convert 112-bit message to 28-char hex string
    function msg_to_hex(msg : std_logic_vector(111 downto 0)) return string is
        variable result : string(1 to 28);
        variable nibble : std_logic_vector(3 downto 0);
    begin
        for i in 0 to 27 loop
            nibble := msg(111 - i*4 downto 108 - i*4);
            result(i+1) := nibble_to_hex(nibble);
        end loop;
        return result;
    end function;

begin

    -- Clock generation
    clock <= not clock after CLK_PERIOD / 2 when not sim_done else '0';

    -- Timestamp counter (provides counter_value to decoder)
    U_timestamp : entity work.timestamp_counter
        generic map (WIDTH => COUNTER_WIDTH)
        port map (
            clock          => clock,
            reset          => reset,
            pps_in         => pps_in,
            counter_value  => counter_value,
            counter_at_pps => counter_at_pps,
            pps_count      => pps_count,
            pps_new        => pps_new
        );

    -- Device Under Test: full decode pipeline
    U_decoder : entity work.adsb_decoder
        generic map (
            NUM_DECODERS => NUM_DEC,
            PREAMBLE_MESSAGE_DELAY => PREAMBLE_MESSAGE_DELAY,
            PREAMBLE_OUTPUT_TAP => PREAMBLE_OUTPUT_TAP
        )
        port map (
            clock         => clock,
            reset         => reset,
            init          => init,
            in_power      => in_power,
            in_valid      => in_valid,
            counter_value => counter_value,
            quiet_score_shift_cfg => to_unsigned(QUIET_SCORE_SHIFT, 3),
            snr_ratio_shift_cfg   => to_unsigned(SNR_RATIO_SHIFT, 3),
            holdoff_cfg           => to_unsigned(PREAMBLE_HOLDOFF_DEFAULT, 12),
            message_delay_cfg      => to_unsigned(PREAMBLE_MESSAGE_DELAY, 8),
            output_tap_cfg         => to_unsigned(PREAMBLE_OUTPUT_TAP, 8),
            debug_rpl     => debug_rpl,
            out_messages  => out_messages,
            out_valid     => out_valid,
            out_toas      => out_toas,
            out_rpls      => out_rpls
        );

    -- =========================================================================
    -- Stimulus: read binary I/Q file and feed power samples
    -- =========================================================================
    stim : process
        type char_file_t is file of character;
        file vec_file : char_file_t;
        variable status : file_open_status;
        variable c : character;
        variable byte0, byte1, byte2, byte3 : integer;
        variable i_val, q_val : integer;
        variable i_s, q_s : signed(15 downto 0);
        variable power : signed(INPUT_POWER_WIDTH-1 downto 0);
        variable i_sq, q_sq : signed(31 downto 0);
        variable sample_count : integer := 0;

        procedure wait_clocks(n : positive) is
        begin
            for i in 1 to n loop
                wait until rising_edge(clock);
            end loop;
        end procedure;
    begin
        -- Reset
        reset <= '1';
        wait_clocks(20);
        reset <= '0';
        wait_clocks(5);

        -- Simulate a PPS pulse early so we have a timestamp reference
        pps_in <= '1';
        wait_clocks(10);
        pps_in <= '0';
        wait_clocks(10);

        -- Open the test vector file
        report "Opening test vector: " & VECTOR_FILE;
        file_open(status, vec_file, VECTOR_FILE, read_mode);
        if status /= open_ok then
            report "ERROR: Could not open " & VECTOR_FILE severity failure;
        end if;

        report "Feeding samples into decoder pipeline...";

        -- Read samples: 4 bytes per sample (I_lo, I_hi, Q_lo, Q_hi), little-endian
        while not endfile(vec_file) loop
            -- Read I (16-bit LE signed)
            read(vec_file, c);
            byte0 := character'pos(c);  -- I low byte
            if endfile(vec_file) then exit; end if;
            read(vec_file, c);
            byte1 := character'pos(c);  -- I high byte

            -- Read Q (16-bit LE signed)
            if endfile(vec_file) then exit; end if;
            read(vec_file, c);
            byte2 := character'pos(c);  -- Q low byte
            if endfile(vec_file) then exit; end if;
            read(vec_file, c);
            byte3 := character'pos(c);  -- Q high byte

            -- Reconstruct 16-bit signed values
            i_val := byte0 + byte1 * 256;
            if i_val >= 32768 then i_val := i_val - 65536; end if;
            q_val := byte2 + byte3 * 256;
            if q_val >= 32768 then q_val := q_val - 65536; end if;

            -- Compute power = I² + Q²
            i_s := to_signed(i_val, 16);
            q_s := to_signed(q_val, 16);
            i_sq := i_s * i_s;
            q_sq := q_s * q_s;
            -- Truncate to INPUT_POWER_WIDTH bits (24-bit, max ~8.4M fits)
            power := resize(i_sq(INPUT_POWER_WIDTH-1 downto 0) +
                           q_sq(INPUT_POWER_WIDTH-1 downto 0),
                           INPUT_POWER_WIDTH);

            -- Feed to decoder
            wait until rising_edge(clock);
            in_power <= power;
            in_valid <= '1';

            sample_count := sample_count + 1;
        end loop;

        -- Stop feeding
        wait until rising_edge(clock);
        in_valid <= '0';
        in_power <= (others => '0');

        file_close(vec_file);
        report "Fed " & integer'image(sample_count) & " samples from " & VECTOR_FILE;

        -- Wait for pipeline to drain (decoders need time to finish CRC brute-force)
        -- Extended message = 112 bits × 16 samples/bit = 1792 samples processing
        -- Plus up to 32 CRC iterations × ~15 clocks each = ~480 clocks
        -- Plus pipeline latency. Be generous: wait 5000 clocks.
        report "Waiting for pipeline to drain...";
        wait_clocks(5000);

        report "== Simulation complete ==";
        sim_done <= true;
        wait;
    end process;

    -- =========================================================================
    -- Monitor: watch for decoded messages on all decoder outputs
    -- =========================================================================
    monitor : process(clock)
        variable msg_count : integer := 0;
    begin
        if rising_edge(clock) then
            for i in 0 to NUM_DEC-1 loop
                if out_valid(i) = '1' then
                    msg_count := msg_count + 1;
                    report "*** DECODED MESSAGE [decoder " &
                           integer'image(i) & "] #" &
                           integer'image(msg_count) & ": " &
                           msg_to_hex(out_messages(i)) &
                           " TOA=" & integer'image(to_integer(out_toas(i)(31 downto 0))) &
                           " RPL=" & integer'image(to_integer(out_rpls(i))) &
                           " at time " & time'image(now);
                end if;
            end loop;
        end if;
    end process;

    -- =========================================================================
    -- Power monitor: report non-zero power samples being fed (first few only)
    -- =========================================================================
    power_mon : process(clock)
        variable reported : integer := 0;
        variable total_valid : integer := 0;
        variable nonzero_count : integer := 0;
    begin
        if rising_edge(clock) then
            if in_valid = '1' then
                total_valid := total_valid + 1;
                if in_power > to_signed(0, INPUT_POWER_WIDTH) then
                    nonzero_count := nonzero_count + 1;
                    if reported < 5 then
                        report "POWER_MON: Sample " & integer'image(total_valid) &
                               " power=" & integer'image(to_integer(in_power));
                        reported := reported + 1;
                    end if;
                end if;
            end if;
            if sim_done and reported >= 0 then
                report "POWER_MON: Total valid=" & integer'image(total_valid) &
                       " nonzero=" & integer'image(nonzero_count);
                reported := -1;  -- prevent repeated reports
            end if;
        end if;
    end process;

end architecture;
